local Items = setmetatable({},{ __mode = "k" });
local ShaqTitles = {
	-- Mods Boot Camp
	["A Moon of Caral (Verdammt Remix)"] = "A Moon of Shaqal (Verdammt Remix)",
	["AΩ"] = "ShaqΩ",
	["AYAKASHI"] = "SHAYAKASHI",
	["Backflow"] = "Shaqflow",
	["Blacksphere"] = "Shaqsphere",
	["Blastix Riotz"] = "Blastix Shaqz",
	["bloom"] = "shaqoom",
	["Catadioptric"] = "Catadiopshaq",
	["Common World Domination"] = "Common World Shaqnation",
	["DEADLOCK XXX"] = "SHAQLOCK XXX",
	["Discloze"] = "Shaqloze",
	["disco KAWAii"] = "shaq KAWAii",
	["dream control"] = "shaq control",
	["ECHO"] = "SHAQ",
	["Firestorm"] = "Shaqstorm",
	["Fly to Next World (syzfonics remix)"] = "Fly to Shaq World (syzfonics remix)",
	["INF-B <<L-aste-R>>"] = "SHAQ-B <<L-aste-R>>",
	["M.A.Y.U."] = "S.H.A.Q.",
	["Opium and Purple Haze"] = "Opium and Shaqle Haze",
	["Pet Peeve"] = "Pet Shaave",
	["Pieces of a Dream"] = "Shaqs of a Dream",
	["Profession"] = "Shafession",
	["Rubeus"] = "Shaqus",
	["Twin Rocket"] = "Shaq Rocket",
	["Warriors Aboot"] = "Shaquille Aboot",

	-- Mods Boot Camp 2
	["Brain Power"] = "Brain Shawer",
	["CENSORED!!"] = "SHAQUILLE!!",
	["continew"] = "shaquille",
	["Crack Traxxxx"] = "Shaq Traxxxx",
	["Crimson Sword Dance"] = "Crimson Shaq Dance",
	["Dawn of Asia"] = "Shaq of Asia",
	["Double Universe"] = "Double Shaqverse",
	["good high school"] = "good shaq school",
	["Grip & Break down!! -SDVX Edit.-"] = "Shaq & Break down!! -SDVX Edit.-",
	["INFINITY OVERDRIVE"] = "SHAQNITY OVERDRIVE",
	["Issen"] = "Shassen",
	["Jump!"] = "Shaq!",
	["KAC 2012 Ultimate Medley Extend -HISTORIA SOUND VOLTEX-"] = "NBA 1992 Ultimate Draft Extend -HISTORIA SHAQUILLE O'NEAL-",
	["Mirai Prism"] = "Shaq Prism",
	["Neko Kuma Usasaa"] = "Neko Kuma Shakakaa",
	["ON FIRE"] = "ON SHAQ",
	["Ops Code -Rapture-"] = "Ops Shaq -Rapture-",
	["Preserved Valkyria"] = "Preserved Shaqyria",
	["Rampage"] = "Shaqpage",
	["Rings of Rainbow"] = "Shaqs of Rainbow",
	["Sayonara Planet Wars"] = "Sayonara Planet Shaqs",
	["Shiawase Transmission"] = "Shaquille Transmission",
	["shiningray"] = "shaqingray",
	["There's Supposed To Be A Cheat Code For Happiness"] = "There's Supposed To Be A Shaq Code For Shaqiness",
	["Virtual Sunrise (xac remix)"] = "Virtual Shanrise (xac remix)",
	["WAVE WAVE WAVE"] = "SHAQ SHAQ SHAQ",
	["XROSS INFECTION"] = "SHAQS INFECTION",
	["XyHATTE"] = "SHaQUILLE",

	-- Mods Boot Camp 3
	["Ayakashi Kakushi"] = "Shayakashi Kakushi",
	["C18H27NO3"] = "S18H27AQ3",
	["citrus"] = "shaqrus",
	["Cloud 9"] = "Shaq 9",
	["Dadadadadadadadadada"] = "Shashashashashashashashashasha",
	["Dark Matter"] = "Dark Shatter",
	["Deadball de Homerun"] = "Basketball de Homerun",
	["Destroy"] = "Shaqtroy",
	["Dopamine"] = "Shaqamine",
	["dreamin' of u"] = "shaquin' of u",
	["Dyscontrolled Galaxy"] = "Dyscontrolled Shaqaxy",
	["Fafnir"] = "Shaqnir",
	["#FairyJoke #SDVX_Edit"] = "#ShaqJoke #SDVX_Edit",
	["Goodbye-bye Planet"] = "Goodbye-bye Shaqnet",
	["Gorgetech"] = "Shaqetech",
	["Got more raves?"] = "Got more shaq?",
	["Hana no motorenga"] = "Shaq no motorenga",
	["HP 1"] = "7 ft 1 in",
	["HYMN"] = "SHAQ",
	["iLLness LiLin"] = "iLLness ShaQin",
	["JUGGLE"] = "SHAGGLE",
	["Junk Mania"] = "Shaq Mania",
	["Kanashibari no ai wo"] = "Kanashibari no shaq wo",
	["Koi hadou? Moro@Hadou OK*Houteishiki!!"] = "Shaq hadou? Shaq@Hadou OK*Houteishiki!!",
	["Kusare gedou to chocolate"] = "Kusare gedou to shaqolate",
	["Le Fruit Defendu"] = "Le Shaqit Defendu",
	["Made In Love"] = "Made In Shaq",
	["Mother Ship (C-YA MIX)"] = "Mother Shaq (C-YA MIX)",
	["Night of knights"] = "Shaq of shaqs",
	["Nishinippori no odori"] = "Shaquille no odori",
	["Nyan Cat"] = "Nyan Shaq",
	["Onii-chan Hi Tech"] = "Onii-chan Hi Shaq",
	["Oriental Mythology Medley"] = "Oriental Shaqology Medley",
	["Planeta Journey"] = "Planeta Sharney",
	["Raiko Thunder Beat"] = "Shaq Thunder Beat",
	["Random Box"] = "Random Shaq",
	["Sailing Force"] = "Shaqing Force",
	["snow motion"] = "shaq motion",
	["Super*Super*Light*Speed*Delivery!!!Speed*Star*Kanade"] = "Super*Super*Light*Speed*Delivery!!!Speed*Star*Shaq",
	["This is the Happiness and Peace of Mind Committee."] = "This is the Happiness and Peace of Shaquille O'Neal.",
	["TRIGGER*HAPPY"] = "TRIGGER*SHAQY",
	["Usatei"] = "Shaqtei",
	["Vigor"] = "Shaqor",
	["Voltex taisou daiichi"] = "Shaq taisou daiichi",
	["We Are The Scarlet"] = "We Are The Shaquille",
	["Wish Upon Twin Stars"] = "Wish Shaq Twin Stars",

	-- OISRT
	["\"Schall\" we step?"] = "\"Shaq\" we step?",
	["Aquarelle 010 (Deemo Ver.)"] = "Shaqrelle 010 (Deemo Ver.)",
	["Biotonic"] = "Shaqnic",
	["Burn"] = "Sharn",
	["Butterfly Planet"] = "Butterfly Shaqnet",
	["Caring Dance"] = "Shaqing Dance",
	["chrono diver -fragment-"] = "chrono diver -shaqment-",
	["Clock Atelier"] = "Shaq Atelier",
	["だんがんろんぱ! NecroDancer REMIX"] = "だんがんろんぱ! ShaqDancer REMIX",
	["Dead Point"] = "Shaq Point",
	["Echoes"] = "Shaqes",
	["Electroman Adventures"] = "Shaqman Adventures",
	["Ensemble Forecast 328"] = "Shaqmble Forecast 328",
	["Foolish Hero"] = "Shaqish Hero",
	["Funny Funky Freaky"] = "Shaqy Shaqy Shaqky",
	["Habanera 1"] = "Shaqnera 1",
	["Holic"] = "Shalic",
	["ILIAS"] = "SHAQS",
	["Jungle City"] = "Jungle Shaqy",
	["Just a Little Smile"] = "Shaq a Little Smile",
	["Kimi no Akari"] = "Shaq no Akari",
	["Kitty From Hell"] = "Kitty From Shaq",
	["ココロボ"] = "シヤツク",
	["Lionheart [A]"] = "Shaqheart [A]",
	["Lionheart [1]"] = "Shaqheart [1]",
	["Lollipop*driveR"] = "Shaqpop*driveR",
	["Nocturnal Type"] = "Nocturnal Shaq",
	["Onegai! Kon kon Oinarisama"] = "Onegai! Kon kon Shaquillesama",
	["Options"] = "Shaqtions",
	["君とpool disco"] = "君とshaq disco",
	["PROPER RHYTHM"] = "SHAQER RHYTHM",
	["Pump!n"] = "Shaq!n",
	["Removable Disk0"] = "Removable Shaq0",
	["S*A*G*A"] = "S*H*A*Q",
	["Sakura Storm"] = "Shaqra Storm",
	["Stepper"] = "Shaqqer",
	["Stratoliner"] = "Shaqratoliner",
	["Tea and Corruption"] = "Shaq and Corruption",
	["Teufel"] = "Shaqfel",
	["Thin Ice"] = "Shaq Ice",
	["雲海"] = "シャク海",
	["VANGUARD-1"] = "SHAQGUARD-1",
	["Wavetapper"] = "Shaqtapper",
	["7thSense"] = "7thShaq",
	["Apollo [1]"] = "Shapollo [1]",
	["Apollo [A]"] = "Shapollo [A]",
	["Bang Pad (Werk Mix)"] = "Shaq Pad (Werk Mix)",
	["ベィスドロップ・フリークス"] = "シャクドロップ・キールス",
	["Believe in Yourself"] = "Believe in Yourshaq",
	["bubble attack"] = "shabble attack",
	["c.s.q.n."] = "s.h.a.q.",
	["CyberConnect"] = "ShaqberConnect",
	["Daisycutter"] = "Shaqycutter",
	["Gamegame"] = "Shaqshaq",
	["GHOUL"] = "SHAQOUL",
	["glacia"] = "shaqacia",
	["Hop Step Adventure"] = "Shaq Shaq Adventure",
	["Hurry Hurry"] = "Shaqy Shaqy",
	["Luminescence"] = "Lumineshaq",
	["Marionette"] = "Shaqionette",
	["Matt Silver"] = "Shaq Silver",
	["MAX... 2048?"] = "MAX... SHAQ?",
	["NAGAREBOSHI*ROCKET"] = "SHAGAREBOSHI*ROCKET",
	["Nanahoshi"] = "Shaqhoshi",
	["Nothing But Theory"] = "Shaq But Theory",
	["Oosanbashi"] = "Shaqanbashi",
	["overcomplexification"] = "overshaqlexification",
	["Per Aspera Ad Astra"] = "Per Shaqra Ad Astra",
	["怪盗Ｆの台本 -消えたダイヤの謎-"] = "怪盗Ｓの台本 -消えたシャックの謎-",
	["PLAY"] = "SHAQ",
	["Portal"] = "Shartal",
	["Puff Piece"] = "Shaq Piece",
	["QLWA"] = "QHSA",
	["Rejection Girl"] = "Rejection Shaq",
	["逆月"] = "シャク月",
	["SAtAN"] = "SHAtAN",
	["シャッキーーン！！"] = "シャッキーール！！",
	["Sigmund"] = "Shaqmund",
	["Singularity"] = "Shaqularity",
	["Sovereign"] = "Shaqreign",
	["Sudden Visitor"] = "Shaqen Visitor",
	["Titania"] = "Shaqnia",
	["TRICKL4SH 220"] = "SHAQL4SH 220",
	["UMMU"] = "SHHS",
	["Urban Constellations"] = "Sharban Constellations",
	["WAMARU - Treaty of Peace Between Boot and Leg"] = "WAMARU - Treaty of Peace Between Boot and Shaq",
	["White Dwarf Stars"] = "White Dwarf Shaqs",
	["WONDER $LOT 777"] = "WONDER $HAQ 777",

	-- OISRT (Translit)
	["Danganronpa! NecroDancer REMIX"] = "Danganronpa! ShaqDancer REMIX",
	["Kokorobo"] = "Shaqorobo",
	["kimi to pool disco"] = "kimi to shaq disco",
	["Unkai"] = "Shaqkai",
	["Bassdrop Freaks"] = "Shaqdrop Quilles",
	["Phantom Thief F's Scenario -Mystery of the Missing Diamond-"] = "Phantom Thief S's Scenario -Mystery of the Missing Shaqamond-",
	["Sakazuki"] = "Shaqazuki",
	["Shakkiiin!!"] = "Shaquiiille!!",
};

function ReplaceSongTitle()
	for k,v in pairs(Items) do
		if v then
			local name = v:GetText();
			if ShaqTitles[name] then
				v:settext(ShaqTitles[name]);
			end
		end
	end
end

function CaptureTitleFromTextBanner(self)
	Items[self] = self;
end

function ClearCaptureTitles(self)
	for k,v in pairs(Items) do
		Items[k] = nil;
	end
	collectgarbage();
end
